// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBxp5xQE0LUmN9cHkPnbCEGAs25hpTjuA',
    appId: '1:513967163990:web:011ac901b0681b82b409f7',
    messagingSenderId: '513967163990',
    projectId: 'genui-flutter-catania',
    authDomain: 'genui-flutter-catania.firebaseapp.com',
    storageBucket: 'genui-flutter-catania.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATOfKC16SQeHiTRxUN1cZXXKSF2snzVww',
    appId: '1:513967163990:android:a76b7ab3dafac9b6b409f7',
    messagingSenderId: '513967163990',
    projectId: 'genui-flutter-catania',
    storageBucket: 'genui-flutter-catania.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN7pEVEVeqU8_MSoqygjMVl8S16WCspNk',
    appId: '1:513967163990:ios:e8f734cc39e8ddbeb409f7',
    messagingSenderId: '513967163990',
    projectId: 'genui-flutter-catania',
    storageBucket: 'genui-flutter-catania.firebasestorage.app',
    iosBundleId: 'com.example.genuiFlutterCatania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN7pEVEVeqU8_MSoqygjMVl8S16WCspNk',
    appId: '1:513967163990:ios:e8f734cc39e8ddbeb409f7',
    messagingSenderId: '513967163990',
    projectId: 'genui-flutter-catania',
    storageBucket: 'genui-flutter-catania.firebasestorage.app',
    iosBundleId: 'com.example.genuiFlutterCatania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBxp5xQE0LUmN9cHkPnbCEGAs25hpTjuA',
    appId: '1:513967163990:web:c86b20b1a9a38a60b409f7',
    messagingSenderId: '513967163990',
    projectId: 'genui-flutter-catania',
    authDomain: 'genui-flutter-catania.firebaseapp.com',
    storageBucket: 'genui-flutter-catania.firebasestorage.app',
  );
}
